### ISSUE TITLE
Consider adding default case to switch statement in _readFmtChunk for improved robustness

### ISSUE THREAD

**Issue by aliciusschroeder** [CR1337/rl-audio-player#17]
## Description
In the file `audio.c`, the function `_readFmtChunk` contains a switch statement starting at line 456 that lacks a default case:

```c
switch (_self->riffData.format) {
    case WAVE_FORMAT_IEEE_FLOAT:
    case WAVE_FORMAT_ALAW:
    case WAVE_FORMAT_MULAW:
        // ...
        break;

    case WAVE_FORMAT_EXTENSIBLE:
        // ...
        break;
}
```

## Considerations
While there are prior checks in the function that should catch invalid formats (around line 428), adding a default case to this switch statement could further improve the robustness and maintainability of the code.

Potential benefits of adding a default case include:
1. Explicit handling of unexpected scenarios, even if they should theoretically never occur
2. Easier debugging if an unforeseen format somehow makes it to this point
3. Improved code clarity for future maintainers

This is a minor issue and more for the sake of defensive programming, given the existing checks. However, addressing it could contribute to the overall quality and resilience of the codebase.

**Comment by CR1337** [comment]
Here we enter philosophical and strongly oppinionated territory. I prefer defensive programming for code that directly interfaces with the outside e.g. an end user. But code that interfaces only with my own code I want to fail if any invariant doesn't hold true. Here I am an advocat for [offensive programming](https://en.wikipedia.org/wiki/Defensive_programming#Offensive_programming), meaning failing loudly in oder to clearly communicate the presence of a fault. 

To be fair Wikipedia confusingly lists offensive programming as a subcategory of defensive programming. Nevertheless I think we both agree that code should clearly communicate its intent and purpose. Therefore I added an always failing assertion to the default branch of the second switch block. Fixed with 9233f5836774153e486bd8b3b2bf8c9ac5c0f6d0
